### ISSUE TITLE
unable to create intervals file

### ISSUE THREAD

**Issue by elmaffo** [sheenams/msings#1]
I am trying to set up msings on a custom analysis.
When I try to create the msi intervals file, target BED file sorting works but then the creation of the intervals file fails (the intervals file is empty) with the following messages:

Making MSI intervals file scripts/custom_regions.msi_intervals
Traceback (most recent call last):
  File "/home/elmaffo/msings/msings-env/bin/msi", line 4, in <module>
    __import__('pkg_resources').run_script('msings==191.302893', 'msi')
  File "/home/elmaffo/msings/msings-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/elmaffo/msings/msings-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/elmaffo/msings/msings-env/lib/python2.7/site-packages/msings-191.302893-py2.7.egg/EGG-INFO/scripts/msi", line 7, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/elmaffo/msings/msings-env/local/lib/python2.7/site-packages/msings-191.302893-py2.7.egg/msings/scripts/script.py", line 32, in main
    return action(arguments)
  File "/home/elmaffo/msings/msings-env/local/lib/python2.7/site-packages/msings-191.302893-py2.7.egg/msings/subcommands/formatter.py", line 57, in action
    chr, beg, end = coords(row)
  File "/home/elmaffo/msings/msings-env/local/lib/python2.7/site-packages/msings-191.302893-py2.7.egg/msings/subcommands/formatter.py", line 32, in coords
    return row[chromosome], int(row[start]), int(row[stop])
ValueError: invalid literal for int() with base 10: 'Start'
Created scripts/custom_regions.msi_intervals

**Comment by elmaffo** [comment]
Addendum: the bed file is in format chr# start stop, not # start stop
